### PR TITLE
Add the has_many association for reviews from a user

### PR DESCRIPTION
**Pull request by dgra**

### CODE REVIEW

**Comment by dgra** [comment]
@tvdeyen I was wondering if I could get this pull request looked at. It just adds the `Spree::User#reviews` has_many relation.

**Comment by dgra** [comment]
Thank you for giving me feedback. 
It is very helpful and I will try harder in the future to avoid `class_eval`.

Also, if this is approved, I will squash these two commits into one.

**Comment by tvdeyen** [comment]
Now that we merged the Solidus 2.3 fixes, could you please rebase your branch on current master? This should fix the build.

Thanks for addressing the feedback

**Comment by dgra** [comment]
I have rebased onto current master and squashed my commits.

Thank you again for providing feedback!

**Comment by tvdeyen** [comment]
Thank you!

**Pull request merged**
